replicaCount: 1
revisionHistoryLimit: 5

image:
  repository: jenkins/jenkins
  tag: "2.541.3-lts-jdk21"
  pullPolicy: IfNotPresent

deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

service:
  type: ClusterIP
  port: 8080
  agentPort: 50000

containerPorts:
  http: 8080
  agent: 50000

serviceAccount:
  create: true
  name: jenkins

ingress:
  enabled: true
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "false"
  hosts:
    - host: jenkins.localhost
      paths:
        - path: /
          pathType: Prefix

persistence:
  enabled: true
  size: 2560Mi
  storageClassName: "standard"
  accessMode: ReadWriteOnce

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

env: []

# Only custom config for env vars
envFrom:
  - configMapRef:
      name: jenkins-custom-config
      optional: true

# Volume mounts for ConfigMaps
extraConfigMapMounts:
  - name: jenkins-jenkins-casc
    mountPath: /etc/config/jenkins-casc.yaml
    subPath: jenkins.yaml
  - name: jenkins-custom-config
    mountPath: /etc/config/jenkins-config.yaml
    subPath: jenkins-config.yaml


agent:
  enabled: true
  image:
    repository: jenkins/inbound-agent
    tag: "latest-jdk17"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi