replicaCount: 1
revisionHistoryLimit: 5

image:
  repository: jenkins/jenkins
  tag: "2.541.3-lts-jdk21"
  pullPolicy: IfNotPresent

extraConfigMapMounts:
  - name: jenkins-custom-config
    mountPath: /etc/config/jenkins-config.yaml
    subPath: jenkins-config.yaml

serviceAccount:
  create: true
  name: jenkins

service:
  type: ClusterIP
  port: 8080
  agentPort: 50000

ingress:
  enabled: true
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "false"
  hosts:
    - host: jenkins.localhost
      paths:
        - path: /
          pathType: Prefix

persistence:
  enabled: true
  size: 2560Mi
  storageClassName: "standard"
  accessMode: ReadWriteOnce

agent:
  enabled: true
  image:
    repository: jenkins/inbound-agent
    tag: "latest-jdk17"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

env: []

casc:
  configMapName: jenkins-jenkins-casc