{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jenkins.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: Replace=false
{{- end }}