apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - name: agent
      port: {{ .Values.service.agentPort }}
      targetPort: agent
      protocol: TCP
  selector:
    {{- include "jenkins.selectorLabels" . | nindent 4 }}